version: '3.8'
services:
  backend:
    image: mp4_to_gif_backend_image:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 5
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  frontend:
    image: mp4_to_gif_frontend_image:latest
    ports:
      - "4200:4200"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
