version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    deploy:
      replicas: 5
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure